// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3r5ZCT9EfP79eV9NfiTWoqKb3zxf7Wbc',
    appId: '1:210843505954:web:095f3ace12d0f6b5f4417b',
    messagingSenderId: '210843505954',
    projectId: 'renappss',
    authDomain: 'renappss.firebaseapp.com',
    storageBucket: 'renappss.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqUX17mwylbUeD_nYk3XVFlXHqo5O_7Fk',
    appId: '1:210843505954:android:5e5c123aed767e45f4417b',
    messagingSenderId: '210843505954',
    projectId: 'renappss',
    storageBucket: 'renappss.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEhvjaxL1y8lHwbhKgbHy4u3puJO-ypa4',
    appId: '1:210843505954:ios:5a7c24b0f26012c9f4417b',
    messagingSenderId: '210843505954',
    projectId: 'renappss',
    storageBucket: 'renappss.appspot.com',
    iosBundleId: 'com.flxdbs.renapps',
  );
}
